### ISSUE TITLE
Can't install patched gcc

### ISSUE THREAD

**Issue by lccambiaghi** [jimeh/build-emacs-for-macos#8]
Hi, in the `.install-patched-gcc` step I get the below brew error:
```
sed -e 's/\(UNUSED\)/_GLIBCXX_\1/g' \
	    -e 's/\(GCC[ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*_H\)/_GLIBCXX_\1/g' \
	    -e 's/SUPPORTS_WEAK/__GXX_WEAK__/g' \
	    -e 's/\([ABCDEFGHIJKLMNOPQRSTUVWXYZ_]*USE_WEAK\)/_GLIBCXX_\1/g' \
	    -e 's,^#include "\(.*\)",#include <bits/\1>,g' \
	    < /private/tmp/gcc-20200828-97942-1gx0d4h/gcc-10.2.0/libstdc++-v3/../libgcc/gthr-posix.h > x86_64-apple-darwin19/bits/gthr-default.h
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:226:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:137:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:142:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1180:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2149:in `stage'
	20: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:82:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:107:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:112:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2169:in `block in stage'
	11: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	10: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2170:in `block (2 levels) in stage'
	 9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1187:in `block in brew'
	 8: from /usr/local/Homebrew/Library/Homebrew/build.rb:174:in `block (2 levels) in install'
	 7: from /Users/luca/git/build-emacs-for-macos/Formula/gcc.rb:89:in `install'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2083:in `mkdir'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	 3: from /Users/luca/git/build-emacs-for-macos/Formula/gcc.rb:95:in `block in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2025:in `block in system': Failed executing: make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:148:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:160:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:407:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:353:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:357:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:305:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```

Any idea why? Thank you very much!

**Comment by jimeh** [comment]
Hmmm, not much off the top of my head. What version of macOS and Xcode (or Xcode Command Line Tools) do you have?

If you don't have the latest version of Xcode (or Xcode CLI tools), try updating just to be safe. Personally it worked on macOS 10.15.6 with Xcode 11.6.

Also for good measure, I just pushed an update to the `install-patched-gcc` helper script which modifies the PATH in an attempt to get the GCC make script use GNU-based variants of tools like `sed` instead of macOS's default BSD variant.

**Comment by lccambiaghi** [comment]
Thank you for trying to help me! Unfortunately I get the same error after pulling that commit.

Our setups are also quite similar: I am on macOS 10.15.5 and XCode 11.5.

**Comment by jimeh** [comment]
Weird, maybe try `brew uninstall gcc` if you already have the regular formula installed? Otherwise, all I can really suggest is trying to install the unpatched variant from source to see if that fails the same way, to at least get some of idea of where the issue might lie, something like this:

```
brew update
brew uninstall gcc
brew install gcc --build-from-source --force
```

**Comment by lccambiaghi** [comment]
I solved my `gcc` installation problem by upgrading the command line tools to the latest version!
